config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  namespace :owner do
    resource :session, only: [:new, :create, :destroy]
    resource :profile, only: [:edit, :update]
    resources :assistants, only: [:index, :show]
    resources :deliveries, except: :destroy
    resources :things, only: [:show, :edit, :update, :destroy]
    resources :shops
  end

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resources :assistants
    resource :profile, only: [:edit, :update]
    resources :deliveries, only: [:index, :show, :edit, :update] do
      resources :things, only: [:new, :create, :update]
    end
    resources :things, only: :show
    resources :shops, only: [:index, :show]
  end

  namespace :assistant do
    resource :session, only: [:new, :create, :destroy]
    resource :accounts, only: :show
    resources :things, only: [:index, :show, :edit, :update]
  end
end

app/models/assistant.rb
class Assistant < User
  validates :first_name, :last_name, :phone_first, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A.+@.+\..+/ }

  belongs_to :shop
  has_many :things, through: :shop
end

app/controllers/admin/assistants_controller.rb
class Admin::AssistantsController < AdminController
  before_action :assistant, only: [:edit, :update, :show, :destroy]

  def index
    @assistants = Assistant.page(params[:page])
  end

  def new
    @assistant = Assistant.new
  end

  def edit
    render :new
  end

  def update
    if @assistant.update(assistant_params)
      redirect_to admin_assistants_path
    else
      render :new
    end
  end

  def create
    @assistant = Assistant.new(assistant_params)
    if @assistant.valid? && @assistant.save
      redirect_to admin_assistants_path
    else
      render :new
    end
  end

  def destroy
    assistant.destroy
    redirect_to admin_assistants_path
  end

  private

  def assistant_params
    params.require(:assistant).permit!
  end

  def assistant
    @assistant = Assistant.find_by(id: params[:id])
  end
end

app/controllers/assistant/accounts_controller.rb
class Assistant::AccountsController < AssistantController
  def show
    params[:from_date] ||= helpers.readable_date(Date.today)
    params[:to_date] ||= helpers.readable_date(Date.today)
    @things = things.sold_in(params[:from_date], params[:to_date])
    # binding.pry
  end

  private

  def things
    @things = current_assistant.things.decorate
  end
end

app/controllers/assistant/sessions_controller.rb
class Assistant::SessionsController < ApplicationController
  def new
    @assistant = Assistant.new
  end

  def create
    if user&.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to assistant_things_path
    else
      redirect_to root_path, notice: 'Invalid password or username.'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    @user_params ||= params.require(:assistant).permit(:email, :password)
  end

  def user
    @user ||= Assistant.find_by(email: user_params[:email])
  end
end

app/controllers/assistant/things_controller.rb
class Assistant::ThingsController < AssistantController
  before_action :thing, only: [:show, :edit, :update]

  def index
    respond_to do |format|
      format.html do
        @things = things.existing.page(params[:page]).decorate
      end
      format.js do
        @things = things.existing_with_uid(params[:uid]).page(params[:page]).decorate
      end
    end
  end

  def show
    @thing = @thing.decorate
  end

  def update
    @thing.sold!
    redirect_to assistant_things_path
  end

  private

  def thing
    @thing = current_assistant.things.find(params[:id])
  end

  def things
    @things = current_assistant.things
  end
end

app/controllers/assistant_controller.rb
class AssistantController < ApplicationController
  layout 'layouts/assistant'

  before_action :require_assistant

  def current_assistant
    @assistant ||= Assistant.find_by(id: session[:user_id])&.decorate
  end
  helper_method :current_assistant

  private

  def require_assistant
    unless current_assistant
      reset_session
      redirect_to root_path
    end
  end
end

app/controllers/owner/assistants_controller.rb
class Owner::AssistantsController < OwnerController
  before_action :assistant, only: :show

  def index
    @assistants = Assistant.page(params[:page])
  end

  private

  def assistant
    @assistant = Assistant.find_by(id: params[:id])
  end
end

app/views/admin/assistants/_assistant.html.slim
tr
  td
    = assistant.email
  td
    = assistant.first_name
  td
    = assistant.last_name
  td
    = assistant.phone_first
  td
    = assistant.phone_second
  td
    = assistant.shop.name
  td
    => link_to 'Подробнее', admin_assistant_path(assistant), class: 'ui positive basic button'
    => link_to 'Редактировать', edit_admin_assistant_path(assistant), class: 'ui brown basic button'
    = link_to 'Удалить', admin_assistant_path(assistant), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui red button'

app/views/admin/assistants/index.html.slim
h1 Assistants

div
  = link_to '+ Add', new_admin_assistant_path, class: 'ui negative basic button'

table.ui.celled.striped.table
  thead
    tr
      th Email
      th Имя
      th Фамилия
      th Осн. номер тел.
      th Доп. номер тел.
      th Магазин
      th
  tbody
    = render partial: 'assistant', collection: @assistants

app/views/admin/assistants/new.html.slim
h1 Assistant

= simple_form_for [:admin, @assistant] do |f|
  = f.input :email
  = f.input :password, label: 'Пароль'
  = f.input :password_confirmation, label: 'Подтверждение пароля'
  = f.input :first_name, label: 'Имя'
  = f.input :last_name, label: 'Фамилия'
  = f.input :phone_first, label: 'Осн. номер тел.'
  = f.input :phone_second, label: 'Доп. номер тел.'
  = f.association :shop, prompt: 'Выберите магазин'
  = f.submit 'Сохранить'

app/views/admin/assistants/show.html.slim
h1 Подробности о продавце

=> @assistant.first_name
= @assistant.last_name