config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  namespace :owner do
    resource :session, only: [:new, :create, :destroy]
    resource :profile, only: [:edit, :update]
    resources :assistants, only: [:index, :show]
    resources :deliveries, except: :destroy
    resources :things, only: [:show, :edit, :update, :destroy]
    resources :shops
  end

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resources :assistants
    resource :profile, only: [:edit, :update]
    resources :deliveries, only: [:index, :show, :edit, :update] do
      resources :things, only: [:new, :create, :update]
    end
    resources :things, only: :show
    resources :shops, only: [:index, :show]
  end

  namespace :assistant do
    resource :session, only: [:new, :create, :destroy]
    resource :accounts, only: :show
    resources :things, only: [:index, :show, :edit, :update]
  end
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  validates :uid, :departure, presence: true

  has_many :things

  scope :by_create, -> { order(:created_at) }
end

app/controllers/admin/deliveries_controller.rb
class Admin::DeliveriesController < AdminController
  before_action :delivery, only: [:edit, :update, :show]

  def index
    @deliveries = Delivery.by_create.page(params[:page])
  end

  def show
    @things = @delivery.things.page(params[:page])
  end

  def update
    if @delivery.update(delivery_params)
      redirect_to admin_deliveries_path
    else
      render :new
    end
  end

  private

  def delivery_params
    params.require(:delivery).permit(:arrival)
  end

  def delivery
    @delivery = Delivery.find_by(id: params[:id])
  end
end

app/controllers/owner/deliveries_controller.rb
class Owner::DeliveriesController < OwnerController
  before_action :delivery, only: [:edit, :update, :show]

  def index
    @deliveries = Delivery.page(params[:page])
  end

  def new
    @delivery = Delivery.new
  end

  def show
    @things = @delivery.things
  end

  def create
    @delivery = Delivery.new(delivery_params)
    if @delivery.valid? && @delivery.save
      redirect_to owner_deliveries_path
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @delivery.update(delivery_params)
      redirect_to owner_deliveries_path
    else
      render :new
    end
  end

  private

  def delivery_params
    params.require(:delivery).permit!
  end

  def delivery
    @delivery = Delivery.find_by(id: params[:id])
  end
end

app/views/admin/deliveries/_delivery.html.slim
tr id="delivery_#{delivery.id}"
  td
    = delivery.uid
  td
    = readable_date(delivery.departure)
  td
    = readable_date(delivery.arrival)
  td
    => link_to 'Подробнее', admin_delivery_path(delivery), class: 'ui positive basic button'
    = link_to 'Редактировать', edit_admin_delivery_path(delivery), class: 'ui brown basic button'

app/views/admin/deliveries/edit.html.slim
h1
  ' Редактировать доставку
  = @delivery.uid

= simple_form_for [current_admin, @delivery], url: admin_delivery_path(@delivery) do |f|
  ' Отправка
  = readable_date(@delivery.departure)
  = f.input :arrival, as: :string, input_html: { value: readable_date(@delivery.arrival) }, placeholder: 'ДД/ММ/ГГГГ'
  = f.submit 'Сохранить'

app/views/admin/deliveries/index.html.slim
h1 Список доставок

table.ui.celled.striped.table
  thead
    tr
      th Уникальный номер
      th Дата отправки
      th Дата прибытия
      th
  tbody
    = render partial: 'delivery', collection: @deliveries

app/views/admin/deliveries/show.html.slim
div
  ' Доставка
  = @delivery.uid

div
  - if @delivery.arrival
    = link_to '+ Add Thing', new_admin_delivery_thing_path(@delivery)

    table
      thead
        tr
          td Названик
          td Описание
          td Дата доставки
          td Магазин
          td изображение
          td Вес
          td
      tbody
        = render partial: 'admin/things/thing', collection: @things