config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  namespace :owner do
    resource :session, only: [:new, :create, :destroy]
    resource :profile, only: [:edit, :update]
    resources :assistants, only: [:index, :show]
    resources :deliveries, except: :destroy
    resources :things, only: [:show, :edit, :update, :destroy]
    resources :shops
  end

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resources :assistants
    resource :profile, only: [:edit, :update]
    resources :deliveries, only: [:index, :show, :edit, :update] do
      resources :things, only: [:new, :create, :update]
    end
    resources :things, only: :show
    resources :shops, only: [:index, :show]
  end

  namespace :assistant do
    resource :session, only: [:new, :create, :destroy]
    resource :accounts, only: :show
    resources :things, only: [:index, :show, :edit, :update]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/views/welcome/index.html.slim
br
br
br
br
.ui.stackable.four.column.grid.centered
  .column.centered
    center
      = link_to 'Войти как Владелец', new_owner_session_path, class: 'ui grey basic button'
  .column.centered
    center
      = link_to 'Войти как Админ', new_admin_session_path, class: 'ui primary button'
  .column.centered
    center
      = link_to 'Войти как продавец', new_assistant_session_path, class: 'ui primary button'