config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  namespace :owner do
    resource :session, only: [:new, :create, :destroy]
    resource :profile, only: [:edit, :update]
    resources :assistants, only: [:index, :show]
    resources :deliveries, except: :destroy
    resources :things, only: [:show, :edit, :update, :destroy]
    resources :shops
  end

  namespace :admin do
    resource :session, only: [:new, :create, :destroy]
    resources :assistants
    resource :profile, only: [:edit, :update]
    resources :deliveries, only: [:index, :show, :edit, :update] do
      resources :things, only: [:new, :create, :update]
    end
    resources :things, only: :show
    resources :shops, only: [:index, :show]
  end

  namespace :assistant do
    resource :session, only: [:new, :create, :destroy]
    resource :accounts, only: :show
    resources :things, only: [:index, :show, :edit, :update]
  end
end

app/models/thing.rb
class Thing < ApplicationRecord
  after_save :track_it

  validates :name, :description, :price, :weight, presence: true
  validates :uid, uniqueness: true, presence: true

  belongs_to :delivery
  belongs_to :shop
  has_many :tracks

  scope :by_create, -> { order(:created_at) }
  scope :existing, -> { where(sold_date: nil) }
  scope :sold_in, -> (from_date, to_date) { where(sold_date: [from_date.to_date.beginning_of_day..to_date.to_date.end_of_day]) }
  scope :with_uid, -> (uid) { where("uid ILIKE ?", "#{uid}%") }
  scope :existing_with_uid, -> (uid) { existing.with_uid(uid) }

  def sold!
    update(sold_date: DateTime.current)
  end

  def upload_image(image)
    image_id = FlickrService.upload(image)
    if image_id
      self.image_id = image_id
      info = FlickrService.get_info(image_id)
      self.image_url = FlickRaw.url_b(info)
      self.image_thumb = FlickRaw.url_t(info)
      self.save
    end
  end

  private

  def track_it
    tracks.create(shop: shop, price: price, discount: discount)
  end
end

app/controllers/admin/things_controller.rb
class Admin::ThingsController < AdminController
  before_action :thing, only: [:show, :edit, :update]
  before_action :back_path, only: [:show, :update, :create]
  before_action :delivery, only: [:new, :create, :update]

  def new
    @thing = Thing.new
    @shops = Shop.pluck(:id, :name)
  end

  def show
    render action: :show, back_path: back_path
  end

  def create
    @thing = delivery.things.build(thing_params)
    if @thing.valid? && @thing.save
      @thing.upload_image(params.dig(:thing, :image).path)
      redirect_to admin_delivery_path(delivery)
    else
      @shops = Shop.pluck(:id, :name)
      render action: :new, back_path: back_path
    end
  end

  def update
    if @thing.update(thing_params)
      if params.dig(:thing, :image) && @thing.image_id
        FlickrService.remove(@thing.image_id)
      end
      @thing.upload_image(params.dig(:thing, :image))
      redirect_to back_path
    else
      render action: :new, back_path: back_path
    end
  end

  private

  def thing
    @thing = Thing.find(params[:id])
  end

  def thing_params
    params.require(:thing).permit(:uid, :shop_id, :name, :description, :price, :weight)
  end

  def back_path
    back_path = params[:back_path]
  end

  def delivery
    @delivery ||= Delivery.find(params[:delivery_id])
  end
end

app/controllers/assistant/things_controller.rb
class Assistant::ThingsController < AssistantController
  before_action :thing, only: [:show, :edit, :update]

  def index
    respond_to do |format|
      format.html do
        @things = things.existing.page(params[:page]).decorate
      end
      format.js do
        @things = things.existing_with_uid(params[:uid]).page(params[:page]).decorate
      end
    end
  end

  def show
    @thing = @thing.decorate
  end

  def update
    @thing.sold!
    redirect_to assistant_things_path
  end

  private

  def thing
    @thing = current_assistant.things.find(params[:id])
  end

  def things
    @things = current_assistant.things
  end
end

app/controllers/owner/things_controller.rb
class Owner::ThingsController < OwnerController
  before_action :thing, only: [:edit, :update, :destroy]

  def show
    @thing = Thing.includes(tracks: :shop).find(params[:id])
    @tracks = @thing.tracks
  end

  def edit
    render action: :edit, back_path: params[:back_path]
  end

  def update
    back_path = params[:back_path]
    if @thing.update(thing_params)
      redirect_to back_path
    else
      render action: :edit, back_path: back_path
    end
  end

  def destroy
    @thing.destroy
    redirect_to params[:back_path]
  end

  private

  def thing
    @thing = Thing.find(params[:id])
  end

  def thing_params
    params.require(:thing).permit(:price, :discount)
  end
end

app/views/admin/things/_thing.html.slim
tr
  td
    = thing.name
  td
    = thing.description
  td
    = link_to thing.delivery.uid, admin_delivery_path(thing.delivery)
  td
    = link_to thing.shop.name, admin_shop_path(thing.shop)
  td
    = thing.image
  td
    = thing.weight
  td
    = link_to 'Детально', admin_thing_path(thing, back_path: request.env['PATH_INFO'])

app/views/admin/things/index.html.slim
h1 Index thing

div
  = link_to '+ Add Thing', new_admin_delivery_thing_path(@delivery)

table
  thead
    tr
      td Название
      td Описание
      td Доставка
      td Магазин
      td Изображение
      td
  tbody
    = render partial: 'thing', collection: @things

app/views/admin/things/new.html.slim
h1 Thing

= simple_form_for [:admin, @delivery, @thing] do |f|
  = f.input :uid, label: 'Уник. номер'
  = f.input :shop_id, collection: @shops, prompt: 'Выберите магазин', label_method: :last, value_method: :first
  = f.input :name, label: 'Название'
  = f.input :description, label: 'Описание'
  = f.input :price, label: 'Цена'
  = f.input :weight, label: 'Вес'
  = f.input :image, as: :file
  = f.submit 'Сохранить'

app/views/admin/things/show.html.slim
h1 Подробно о товаре

div
  = link_to 'Назад', params[:back_path]
div
  = @thing.name
div
  = image_tag(@thing.image_url) if @thing.image_url